### ISSUE TITLE
Vấn đề về giao diện

### ISSUE THREAD

**Issue by TomAKA2109** [ultimateBroK/fuze_music_player#12]
Hiện tại các nút hiện tại đang chỉ có icon, đồng thời đang bị sát nhau và bé quá

**Comment by ultimateBroK** [comment]
ông thử share ảnh lên tôi check nhoé

**Comment by TomAKA2109** [comment]
> ông thử share ảnh lên tôi check nhoé

tôi làm ổn, xong hết r nhé
