### ISSUE TITLE
Thiết kế và lập trình các tính năng giao diện người dùng

### ISSUE THREAD

**Issue by TomAKA2109** [ultimateBroK/fuze_music_player#7]
Xử lý các giao diện tab mẹ "For you" và các tab con "History", "Last added"

**Comment by ultimateBroK** [comment]
![Image](https://github.com/ultimateBroK/fuze_music_player/assets/67256125/6e9cbb0e-6060-45d1-9157-88d152bb19a0)



![Image](https://github.com/ultimateBroK/fuze_music_player/assets/67256125/afb2198f-986c-4001-b0e3-d098b0dfa520)

**Comment by TomAKA2109** [comment]
Các nút hiện tại đang chỉ có icon, đồng thời đang bị sát nhau và bé quá
